"""Adicionar campo atendente em solicitacao

Revision ID: 1cbfe916fbe7
Revises: e92331e601f6
Create Date: 2025-04-14 11:04:20.418007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cbfe916fbe7'
down_revision = 'e92331e601f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atendente', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.drop_column('atendente')

    # ### end Alembic commands ###
