"""Remover os campos datahora e horario_inicio

Revision ID: 25b198d3ba58
Revises: fd36278c81dd
Create Date: 2025-03-31 17:14:17.765615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b198d3ba58'
down_revision = 'fd36278c81dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.drop_column('datahora')
        batch_op.drop_column('horario_inicio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horario_inicio', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('datahora', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
