"""Adicionando coluna sender_type em ChatMessage

Revision ID: 3a76cebb247c
Revises: 
Create Date: 2025-03-25 14:43:40.741737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a76cebb247c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('recipient', sa.String(length=100), nullable=True))
        batch_op.alter_column('sender',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('sender',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('recipient')
        batch_op.drop_column('sender_type')

    # ### end Alembic commands ###
