"""empty message

Revision ID: 453a4d810f88
Revises: 5b4f47701360
Create Date: 2025-04-07 16:07:56.586361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453a4d810f88'
down_revision = '5b4f47701360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_solicitacao')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atendente', sa.String(length=100), nullable=True))
        batch_op.drop_column('classe')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classe', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('atendente')

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    op.create_table('_alembic_tmp_solicitacao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('setor', sa.VARCHAR(length=50), nullable=True),
    sa.Column('qra', sa.VARCHAR(length=50), nullable=True),
    sa.Column('solicitacao', sa.TEXT(), nullable=True),
    sa.Column('prioridade', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('imagem', sa.VARCHAR(length=200), nullable=True),
    sa.Column('datahora', sa.DATETIME(), nullable=True),
    sa.Column('horario_inicio', sa.DATETIME(), nullable=True),
    sa.Column('datahora_fim', sa.DATETIME(), nullable=True),
    sa.Column('classe', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
