"""Adicionando novas colunas na tabela solicitacao

Revision ID: 5b4f47701360
Revises: fd36278c81dd
Create Date: 2025-04-01 20:29:26.069814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4f47701360'
down_revision = 'fd36278c81dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        # Adiciona a coluna 'classe' como nullable=True (aceitando valores NULL)
        batch_op.add_column(sa.Column('classe', sa.String(length=100), nullable=True))

    # Aqui você pode fazer a atualização dos valores existentes (se necessário)
    # Exemplo: op.execute("UPDATE solicitacao SET classe = 'default_value' WHERE classe IS NULL")

    # Agora, altere a coluna 'classe' para nullable=False (não permitindo valores NULL)
    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.alter_column('classe', nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.drop_column('email_prefeitura')
        batch_op.drop_column('classe')

    # ### end Alembic commands ###
