"""empty message

Revision ID: e92331e601f6
Revises: 
Create Date: 2025-04-10 11:23:55.824233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92331e601f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=False),
    sa.Column('sender_type', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('recipient', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setor', sa.String(length=50), nullable=True),
    sa.Column('qra', sa.String(length=50), nullable=True),
    sa.Column('solicitacao', sa.Text(), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('imagem', sa.String(length=200), nullable=True),
    sa.Column('datahora', sa.DateTime(), nullable=True),
    sa.Column('horario_inicio', sa.DateTime(), nullable=True),
    sa.Column('datahora_fim', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('senha', sa.String(length=120), nullable=False),
    sa.Column('permissao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('solicitacao')
    op.drop_table('chat_message')
    # ### end Alembic commands ###
