"""Adicionando modelo ChatMessage

Revision ID: fd36278c81dd
Revises: 
Create Date: 2025-03-31 16:28:34.097483

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'fd36278c81dd'
down_revision = None
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=False),
    sa.Column('sender_type', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    # ### end Alembic commands ###
